spring:
  datasource:
    username: irenkia@crudserver
    password: superhero@54321
    url: jdbc:sqlserver://crudserver.database.windows.net:1433;database=crud;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 9191

